# Generated by Django 5.1.7 on 2025-10-12 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', message='Le numéro doit contenir exactement 7 chiffres.')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('classe', models.CharField(blank=True, max_length=100, null=True)),
                ('email_institutionnel', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
