# Generated by Django 5.1.7 on 2025-10-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authorizedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedstudent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
