# Generated by Django 5.1.7 on 2025-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authorizedstudent_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAuthorizedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_institutionnel', models.EmailField(max_length=254)),
                ('date_deleted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
