# Generated by Django 5.1.7 on 2025-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deletedauthorizedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialstudent',
            name='classe',
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='birth_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='identité',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
