# Generated by Django 5.1.7 on 2025-10-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_officialstudent_classe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialstudent',
            name='identité',
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='identite',
            field=models.CharField(default=222, max_length=20),
            preserve_default=False,
        ),
    ]
