# Generated by Django 5.1.7 on 2025-10-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentchoice',
            old_name='num_inscription',
            new_name='inscription',
        ),
    ]
