# Generated by Django 5.1.7 on 2025-11-23 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_num_inscription_studentchoice_inscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officialstudent',
            name='credit_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='diagnostic_financier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='fondamentaux_management',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='fondamentaux_marketing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='gestion_production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='math_financieres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='moyenne_generale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='moyenne_semestre1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='moyenne_semestre2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='principe_gestion1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='principe_gestion2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='resultat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='type_reussite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentchoice',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentchoice',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
