# Generated by Django 5.1.7 on 2025-11-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_officialstudent_credit_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialstudent',
            name='specialite_choisit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
