# Generated by Django 5.1.7 on 2025-11-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_officialstudent_prediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialstudent',
            old_name='credit_total',
            new_name='credit_2emme',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='math_financieres',
            new_name='mathematiques_financieres',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='moyenne_generale',
            new_name='moyenne_elements_specifiques',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='moyenne_semestre1',
            new_name='moyenne_generale_2emme',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='moyenne_semestre2',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='officialstudent',
            name='resultat',
        ),
        migrations.RemoveField(
            model_name='officialstudent',
            name='type_reussite',
        ),
    ]
