# Generated by Django 5.1.7 on 2025-11-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_credit_total_officialstudent_credit_2emme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialstudent',
            old_name='credit_2emme',
            new_name='Credit_totale_2emme',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='gestion_production',
            new_name='Principe_de_gestion_1',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='fondamentaux_management',
            new_name='fondamentaux_du_managment',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='fondamentaux_marketing',
            new_name='fondamenteaux_du_marketing',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='principe_gestion1',
            new_name='gestion_de_production',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='principe_gestion2',
            new_name='principe_de_gestion_2',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='score',
            new_name='scrore',
        ),
    ]
