# Generated by Django 5.1.7 on 2025-11-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_credit_2emme_officialstudent_credit_totale_2emme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialstudent',
            old_name='mathematiques_financieres',
            new_name='Mathematiques_financieres',
        ),
    ]
