# Generated by Django 5.1.7 on 2025-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_mathematiques_financieres_officialstudent_mathematiques_financieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialstudent',
            name='fondamentaux_du_managment',
            field=models.FloatField(blank=True, db_column='fondamentaux_du_managment', null=True),
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='fondamentaux_du_managment',
            new_name='fondamentaux_management',
        ),
        migrations.AlterField(
            model_name='officialstudent',
            name='fondamenteaux_du_marketing',
            field=models.FloatField(blank=True, db_column='fondamenteaux_du_marketing', null=True),
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='fondamenteaux_du_marketing',
            new_name='fondamentaux_marketing',
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='Mathematiques_financieres',
            new_name='gestion_production',
        ),
        migrations.AlterField(
            model_name='officialstudent',
            name='Principe_de_gestion_1',
            field=models.FloatField(blank=True, db_column='Principe_de_gestion_1', null=True),
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='Principe_de_gestion_1',
            new_name='principe_gestion1',
        ),
        migrations.AlterField(
            model_name='officialstudent',
            name='principe_de_gestion_2',
            field=models.FloatField(blank=True, db_column='principe_de_gestion_2', null=True),
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='principe_de_gestion_2',
            new_name='principe_gestion2',
        ),
        migrations.AlterField(
            model_name='officialstudent',
            name='scrore',
            field=models.FloatField(blank=True, db_column='scrore', null=True),
        ),
        migrations.RenameField(
            model_name='officialstudent',
            old_name='scrore',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='officialstudent',
            name='Credit_totale_2emme',
        ),
        migrations.RemoveField(
            model_name='officialstudent',
            name='gestion_de_production',
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='credit_2emme',
            field=models.IntegerField(blank=True, db_column='Credit_totale____2emme', null=True),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='mathematiques_financieres',
            field=models.FloatField(blank=True, db_column='Mathematiques_financieres', null=True),
        ),
        migrations.AlterField(
            model_name='officialstudent',
            name='diagnostic_financier',
            field=models.FloatField(blank=True, db_column='diagnostic__financier', null=True),
        ),
        migrations.AlterField(
            model_name='officialstudent',
            name='moyenne_generale_2emme',
            field=models.FloatField(blank=True, db_column='Moyenne_generale__2emme', null=True),
        ),
    ]
