# Generated by Django 5.1.7 on 2025-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_officialstudent_fondamentaux_du_managment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialstudent',
            name='decision_admin',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('refused', 'Refusé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='officialstudent',
            name='specialite_finale',
            field=models.CharField(blank=True, help_text='La spécialité finale décidée par l’administration', max_length=100, null=True),
        ),
    ]
